products = [
    {
        "name": "彈性牛仔褲",
        "price": 690,
        "description": "運動也沒問題",
        "image": "/assets/clothes/men/bottom/1_1.jpeg",
        "category": "men_bottom",
        "size": "M",
        "color": "黃",
        "tag": "復古、男友風、古著",
        "owner_id": "3",
        "id": "1"
    },
    {
        "name": "深色牛仔寬庫",
        "price": 790,
        "description": "超級古著，vintage",
        "image": "/assets/clothes/men/bottom/2_1.jpeg",
        "category": "men_bottom",
        "size": "M",
        "color": "黃",
        "tag": "復古、男友風、古著",
        "owner_id": "1",
        "id": "2"
    },
    {
        "name": "舒適白色短褲",
        "price": 590,
        "description": "夏天必備，超級舒適",
        "image": "/assets/clothes/men/bottom/3_1.jpeg",
        "category": "men_bottom",
        "size": "M",
        "color": "黃",
        "tag": "復古、男友風、古著",
        "owner_id": "2",
        "id": "3"
    },
    {
        "name": "牛仔短褲",
        "price": 690,
        "description": "潮男必買，人手一條",
        "image": "/assets/clothes/men/bottom/4_1.jpeg",
        "category": "men_bottom",
        "size": "M",
        "color": "黃",
        "tag": "復古、男友風、古著",
        "owner_id": "2",
        "id": "4"
    },
    {
        "name": "刷色牛仔褲",
        "price": 790,
        "description": "個性Cow Boy必買",
        "image": "/assets/clothes/men/bottom/5_1.jpeg",
        "category": "men_bottom",
        "size": "M",
        "color": "黃",
        "tag": "復古、男友風、古著",
        "owner_id": "1",
        "id": "5"
    },
    {
        "name": "特殊材質防風外套",
        "price": 790,
        "description": "材質超特殊的啦",
        "image": "/assets/clothes/men/top/1_1.jpeg",
        "category": "men_top",
        "size": "M",
        "color": "黃",
        "tag": "復古、男友風、古著",
        "owner_id": "1",
        "id": "6"
    },
    {
        "name": "黃色衛衣",
        "price": 490,
        "description": "黃色是一定要有的吧!",
        "image": "/assets/clothes/men/top/2_1.jpeg",
        "category": "men_top",
        "size": "M",
        "color": "黃",
        "tag": "復古、男友風、古著",
        "owner_id": "1",
        "id": "7"
    },
    {
        "name": "棉質運動外套",
        "price": 800,
        "description": "基本款必備 !",
        "image": "/assets/clothes/men/top/3_1.jpeg",
        "category": "men_top",
        "size": "M",
        "color": "黃",
        "tag": "復古、男友風、古著",
        "owner_id": "3",
        "id": "8"
    },
    {
        "name": "米色連帽T恤",
        "price": 690,
        "description": "暖男必備",
        "image": "/assets/clothes/men/top/4_1.jpeg",
        "category": "men_top",
        "size": "M",
        "color": "黃",
        "tag": "復古、男友風、古著",
        "owner_id": "1",
        "id": "9"
    },
    {
        "name": "髒灰色連帽衛衣",
        "price": 490,
        "description": "內刷毛，寒流沒在怕",
        "image": "/assets/clothes/men/top/5_1.jpeg",
        "category": "men_top",
        "size": "M",
        "color": "黃",
        "tag": "復古、男友風、古著",
        "owner_id": "3",
        "id": "10"
    },
    {
        "name": "紅色直條紋五分褲",
        "price": 590,
        "description": "Zala 新款 M 號",
        "image": "/assets/clothes/women/bottom/1_1.jpeg",
        "category": "women_bottom",
        "size": "M",
        "color": "黃",
        "tag": "復古、男友風、古著",
        "owner_id": "1",
        "id": "11"
    },
    {
        "name": "蕾絲褲管牛仔寬庫",
        "price": 690,
        "description": "酷炫牛仔拼接氣質蕾絲 !",
        "image": "/assets/clothes/women/bottom/2_1.jpeg",
        "category": "women_bottom",
        "size": "M",
        "color": "黃",
        "tag": "復古、男友風、古著",
        "owner_id": "3",
        "id": "12"
    },
    {
        "name": "車線真理褲",
        "price": 390,
        "description": "辣妹必買，辣翻炎炎夏天!",
        "image": "/assets/clothes/women/bottom/3_1.jpeg",
        "category": "women_bottom",
        "size": "M",
        "color": "黃",
        "tag": "復古、男友風、古著",
        "owner_id": "2",
        "id": "13"
    },
    {
        "name": "氣質無袖連身褲",
        "price": 490,
        "description": "超級氣質，透氣棉質",
        "image": "/assets/clothes/women/bottom/4_1.jpeg",
        "category": "women_bottom",
        "size": "M",
        "color": "黃",
        "tag": "復古、男友風、古著",
        "owner_id": "2",
        "id": "14"
    },
    {
        "name": "優雅紫色捲邊洋裝",
        "price": 590,
        "description": "約會必穿，男友眼神離不開你 !",
        "image": "/assets/clothes/women/bottom/5_1.jpeg",
        "category": "women_bottom",
        "size": "M",
        "color": "黃",
        "tag": "復古、男友風、古著",
        "owner_id": "1",
        "id": "15"
    },
    {
        "name": "翹臀淺色牛仔寬褲",
        "price": 590,
        "description": "衣櫃裡必須要有一件，超級顯臀",
        "image": "/assets/clothes/women/bottom/6_1.jpeg",
        "category": "women_bottom",
        "size": "M",
        "color": "黃",
        "tag": "復古、男友風、古著",
        "owner_id": "2",
        "id": "16"
    },
    {
        "name": "翻領包臀洋裝",
        "price": 490,
        "description": "超顯身材，展現你的自信",
        "image": "/assets/clothes/women/bottom/7_1.jpeg",
        "category": "women_bottom",
        "size": "M",
        "color": "黃",
        "tag": "復古、男友風、古著",
        "owner_id": "1",
        "id": "17"

    },
{
        "name": "個性紅西裝外套",
        "price": 590,
        "description": "Zala 新款 M 號",
        "image": "/assets/clothes/women/top/1_1.jpeg",
        "category": "women_top",
        "size": "M",
        "color": "黃",
        "tag": "復古、男友風、古著",
        "owner_id": "1",
        "id": "18"
    },
    {
        "name": "假兩件格紋毛衣",
        "price": 490,
        "description": "Zala 新款 s 號，保暖好看又好穿 !",
        "image":"/assets/clothes/women/top/2_1.jpeg",
        "category": "women_top",
        "size": "M",
        "color": "黃",
        "tag": "復古、男友風、古著",
        "owner_id": "1",
        "id": "19"
    },
    {
        "name": "粉色棉質襯衫",
        "price": 350,
        "description": "夏季必買、時尚單品 !",
        "image": "/assets/clothes/women/top/3_1.jpeg",
        "category": "women_top",
        "size": "M",
        "color": "黃",
        "tag": "復古、男友風、古著",
        "owner_id": "1",
        "id": "20"
    },
    {
        "name": "顯眼黃色上衣",
        "price": 490,
        "description": "環保材質，吸爆路人眼球",
        "image": "/assets/clothes/women/top/4_1.jpeg",
        "category": "women_top",
        "size": "M",
        "color": "黃",
        "tag": "復古、男友風、古著",
        "owner_id": "3",
        "id": "21"
    },
    {
        "name": "今天必買奶茶色襯衫",
        "price": 400,
        "description": "文青必備，好看單品",
        "image": "/assets/clothes/women/top/5_1.jpeg",
        "category": "women_top",
        "size": "M",
        "color": "黃",
        "tag": "復古、男友風、古著",
        "owner_id": "1",
        "id": "22"
    },
    {
        "name": "特殊剪裁襯衫",
        "price": 590,
        "description": "襯衫控必備，超越白襯衫的存在",
        "image": "/assets/clothes/women/top/6_1.jpeg",
        "category": "women_top",
        "size": "M",
        "color": "黃",
        "tag": "復古、男友風、古著",
        "owner_id": "2",
        "id": "23"
    }
]
